---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fritt.
--- DateTime: 24.05.2022 18:42
---

function myf()
    local player = getSpecificPlayer(0)
    player:Say("Hello World")
end