---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by fritt.
--- DateTime: 24.05.2022 18:42
---

local function OnObjectAdded(addedObject)
    local object = addedObject;
    local sprite = object:getSprite();
    print("spam");
    if sprite then
        local properties = sprite:getProperties();
        if properties ~= nil and properties:Is("fuelAmount") then
            print(object.spriteName);
            print("hello world");
        end
    end
end

Events.OnObjectAdded.Add(OnObjectAdded);

local function Spammer()
    local player = getSpecificPlayer();
    player:Say("Hello World");
    print("I like trains!");
end

Events.EveryTenMinutes.Add(Spammer);